version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: atlas-backend
    # env_file:
    #   - ./backend/.env
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./atlas-app
    container_name: atlas-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
