# Generated by Django 5.2.5 on 2025-08-20 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolPaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("student_first_name", models.CharField(max_length=64)),
                ("student_last_name", models.CharField(max_length=64)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_id", models.CharField(max_length=64)),
                ("student_id_type", models.CharField(max_length=64)),
                ("student_id_expired_at", models.DateField()),
                ("student_document", models.TextField()),
                ("country_paying_from", models.CharField(max_length=64)),
                ("country_paying_to", models.CharField(max_length=64)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payer", models.CharField(max_length=64)),
                ("payer_id_type", models.CharField(max_length=64)),
                ("payer_id_expired_at", models.DateField()),
                ("payer_id_document", models.TextField()),
                ("university", models.CharField(max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                        ],
                        default="penidng",
                        max_length=10,
                    ),
                ),
                ("payment_receipt", models.TextField(null=True)),
            ],
        ),
    ]
