# Generated by Django 5.2.5 on 2025-08-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="country_paying_from",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="country_paying_to",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="name",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payer_id_document",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payer_id_expired_at",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payer_id_type",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payment_receipt",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="student_document",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="student_id_expired_at",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="student_id_type",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentrequest",
            name="university",
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="amount_cad",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="amount_ngn",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="country_from",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_city",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_first_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_last_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_expected_year_of_completion",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_institution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_personal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="student_program_studied",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
