# Generated by Django 5.2.5 on 2025-08-26 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_schoolpaymentrequest_country_paying_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolPaymentRequestInitializer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("pending", "pending"), ("completed", "completed")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payment_initializer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.schoolpaymentrequestinitializer",
            ),
        ),
    ]
