# Generated by Django 5.2.5 on 2025-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_schoolpaymentrequestinitializer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payment_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("initiated", "initiated"),
                    ("processing", "processing"),
                    ("in-transit", "in-transit"),
                    ("delivered", "delivered"),
                    ("confirmed", "confirmed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
