# Generated by Django 5.2.5 on 2025-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_currency_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="admission_letter_documents",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="payer_id_documents",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="schoolpaymentrequest",
            name="supporting_documents",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
